import BtnSuggestion from "@/components/button/btn-suggestion";
import QueryClientProvider from "@/context/react-query/QueryClientProvider";
import SessionWrapper from "@/lib/SessionWrapper";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL("http://localhost:3000"),
  keywords: ["Keyword 1", "Keyword 2"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased size-full`}
        >
          <NextTopLoader />
          <QueryClientProvider>{children}</QueryClientProvider>
          <BtnSuggestion />
        </body>
      </html>
    </SessionWrapper>
  );
}
